"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

command_timeout="600"

[character]
success_symbol = '[~\$](bold green) '
error_symbol = '[~\$](bold red) '

[directory]
truncation_length = 1
read_only = "󰑇 "
format = "[$path](bold mauve)[$lock_symbol]($lock_style) "

[git_commit]
commit_hash_length = 8
style = "bold text"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = " x${count} "
behind = " x${count} "
conflicted = "󰞇 "
modified = " x${count} "
untracked = " x${count} "
stashed = " x${count} "
staged = " x${count} "
diverged = "󰃻 x${count} "
renamed = "󰑕 x${count} "
deleted = "󰆴 x${count} "
style = "bold sky"
format = "[$all_status](bold teal)[$ahead_behind](bold peach)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol]($style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = 'via [$symbol]($style)'

[elm]
symbol = " "

[git_branch]
symbol = " "
# format = "on [$symbol$branch]($style) "
style = "bold sky"

[golang]
symbol = " "
format = 'via [$symbol]($style)'

[hg_branch]
symbol = " "

[java]
symbol = " "
format = 'via [$symbol]($style)'

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = 'via [$symbol]($style)'

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "

[rust]
format = 'via [$symbol]($style)'

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
format = 'via [$symbol]($style)'
