"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 1
read_only = " "
format = "[$path](bold blue)[$lock_symbol]($lock_style) "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = " x${count} "
behind = " x${count} "
conflicted = "ﲅ "
modified = " x${count} "
untracked = " x${count} "
stashed = " x${count} "
staged = " x${count} "
diverged = " x${count} "
renamed = "凜 x${count} "
deleted = "﫧 x${count} "
style = "bold cyan"
format = "[$all_status](bold cyan)[$ahead_behind](bold red)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol]($style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = 'via [$symbol]($style)'

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
format = 'via [$symbol]($style)'

[hg_branch]
symbol = " "

[java]
symbol = " "
format = 'via [$symbol]($style)'

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = 'via [$symbol]($style)'

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "

[rust]
format = 'via [$symbol]($style)'

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
format = 'via [$symbol]($style)'
